---
# Digital Ocean Monitoring

# FIXME: Make this conditional on some var

- name: ensure do-agent apt repository public key is installed
  apt_key:
    url: "https://repos.sonar.digitalocean.com/sonar-agent.asc"
    state: present

- name: ensure do-agent apt repository is enabled
  apt_repository:
    repo: "deb https://repos.sonar.digitalocean.com/apt main main"
    filename: "digitalocean-agent.list"
    update_cache: true
    state: present

- name: ensure do-agent packages are installed
  apt:
    name: do-agent
    state: latest

- name: ensure do-agent service is started and enabled
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items: do-agent
