---
- name: Install Common build tools
  apt: pkg={{ item }} state=installed
  with_items:
    - parallel
    - apt-transport-https
    - build-essential
    - git
    - curl
    - wget
    - openssl
    - unattended-upgrades

# https://help.ubuntu.com/lts/serverguide/automatic-updates.html
# https://debian-handbook.info/browse/stable/sect.regular-upgrades.html
- name: Enable unattended upgrades
  template: src=apt_periodic.j2 dest=/etc/apt/apt.conf.d/10periodic
            mode=0644 owner=root group=root

- name: Install Apticron
  apt: pkg=apticron state=installed

- name: Configure Apticron
  template: src=apticron.conf.j2 dest=/etc/apticron/apticron.conf

- name: Allow non-root login by public key only
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "{{ item.line }}"
    state: "{{ item.state }}"
  with_items:
    - { line: "PermitRootLogin yes", state: absent }
    - { line: "PubkeyAuthentication no", state: absent }
    - { line: "PasswordAuthentication yes", state: absent }
    - { line: "PermitRootLogin no", state: present }
    - { line: "PubkeyAuthentication yes", state: present }
    - { line: "PasswordAuthentication no", state: present }
