---
- name: 'Provision interkonect server'
  hosts: interkonect.com
  remote_user: "{{ admin_user }}"
  gather_facts: False
  become: True
  vars_files:
    - ../../vars/defaults.yml
  roles:
    - ../roles/bootstrap
    - ../roles/common
    - ../roles/firewall
    - ../roles/metrics
    - ../roles/apache
    - ../roles/lets-encrypt
    - ../roles/hugo
    - ../roles/assets
