- name: "Install UFW (Firewall)"
  apt: name=ufw state=installed

- name: "Limit connection attempts to port 22 (SSH)"
  ufw:
    rule: limit
    port: 22
    proto: tcp

- name: "Open port 22 (SSH)"
  ufw:
    rule: allow
    port: 22
    proto: tcp

- name: "Open port 80 (HTTP)"
  ufw: 
    rule: allow
    port: 80
    proto: tcp

- name: "Open port 443 (HTTPS)"
  ufw: 
    rule: allow
    port: 443
    proto: tcp


- name: "Reject unknown ports by default and enable UFW"
  ufw:
    state: enabled
    policy: reject
