---
- name: 'Deploy teamcoding website'
  hosts: interkonect.com
  remote_user: "{{ admin_user }}"
  gather_facts: False
  become: True
  vars_files:
    - ../../vars/defaults.yml
  vars:
    project: teamcoding
    domain: new.teamcoding.com
    # domain_aliases:
    #   - www.teamcoding.com
    repo: https://github.com/krisleech/new-teamcoding.git
    branch: master
    env: production
    deploy_to: "/home/{{ deploy_user }}/apps/{{ project }}/{{ env }}"
    document_root: "{{ deploy_to }}/public"
    build_command: "hugo --baseURL https://{{ domain }}"
  roles:
    - role: ../roles/static-website
    - role: ../roles/lets-encrypt
